# Generated by Django 5.0.5 on 2024-05-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatoprofessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Digite o telefone do professor', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='Digite o email do professor', max_length=254, verbose_name='Email')),
                ('horario_atend', models.CharField(help_text='Digite o horário de atendimento do professor', max_length=100, verbose_name='Horário de Atendimento')),
                ('nome', models.CharField(help_text='Digite o nome do professor', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
