# Generated by Django 5.0.5 on 2024-05-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título da notificação', max_length=255, verbose_name='Título')),
                ('assunto', models.TextField(help_text='Digite o assunto da notificação', verbose_name='Assunto')),
                ('lida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
