# Generated by Django 5.0.2 on 2024-08-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contato', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(help_text='Digite o nome da materia', max_length=100, verbose_name='Nome')),
                ('professor', models.ForeignKey(blank=True, help_text='Selecione o professor da materia', null=True, on_delete=django.db.models.deletion.CASCADE, to='contato.contato', verbose_name='Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
            },
        ),
    ]
