# Generated by Django 5.0.5 on 2024-05-23 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título do evento', max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Digite a descrição do evento', verbose_name='Descrição')),
                ('data', models.DateTimeField(help_text='Digite a data do evento', verbose_name='Data do envento')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
